/*
Moodle Webservice API

Auto-generated OpenAPI spec for Moodle's Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.

API version: 4.3.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package moodleclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ToolMobileCallExternalFunctionsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ToolMobileCallExternalFunctionsRequest{}

// ToolMobileCallExternalFunctionsRequest struct for ToolMobileCallExternalFunctionsRequest
type ToolMobileCallExternalFunctionsRequest struct {
	Requests []ToolMobileCallExternalFunctionsRequestRequestsInner `json:"requests"`
}

type _ToolMobileCallExternalFunctionsRequest ToolMobileCallExternalFunctionsRequest

// NewToolMobileCallExternalFunctionsRequest instantiates a new ToolMobileCallExternalFunctionsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewToolMobileCallExternalFunctionsRequest(requests []ToolMobileCallExternalFunctionsRequestRequestsInner) *ToolMobileCallExternalFunctionsRequest {
	this := ToolMobileCallExternalFunctionsRequest{}
	this.Requests = requests
	return &this
}

// NewToolMobileCallExternalFunctionsRequestWithDefaults instantiates a new ToolMobileCallExternalFunctionsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewToolMobileCallExternalFunctionsRequestWithDefaults() *ToolMobileCallExternalFunctionsRequest {
	this := ToolMobileCallExternalFunctionsRequest{}
	return &this
}

// GetRequests returns the Requests field value
func (o *ToolMobileCallExternalFunctionsRequest) GetRequests() []ToolMobileCallExternalFunctionsRequestRequestsInner {
	if o == nil {
		var ret []ToolMobileCallExternalFunctionsRequestRequestsInner
		return ret
	}

	return o.Requests
}

// GetRequestsOk returns a tuple with the Requests field value
// and a boolean to check if the value has been set.
func (o *ToolMobileCallExternalFunctionsRequest) GetRequestsOk() ([]ToolMobileCallExternalFunctionsRequestRequestsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Requests, true
}

// SetRequests sets field value
func (o *ToolMobileCallExternalFunctionsRequest) SetRequests(v []ToolMobileCallExternalFunctionsRequestRequestsInner) {
	o.Requests = v
}

func (o ToolMobileCallExternalFunctionsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ToolMobileCallExternalFunctionsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["requests"] = o.Requests
	return toSerialize, nil
}

func (o *ToolMobileCallExternalFunctionsRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"requests",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varToolMobileCallExternalFunctionsRequest := _ToolMobileCallExternalFunctionsRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varToolMobileCallExternalFunctionsRequest)

	if err != nil {
		return err
	}

	*o = ToolMobileCallExternalFunctionsRequest(varToolMobileCallExternalFunctionsRequest)

	return err
}

type NullableToolMobileCallExternalFunctionsRequest struct {
	value *ToolMobileCallExternalFunctionsRequest
	isSet bool
}

func (v NullableToolMobileCallExternalFunctionsRequest) Get() *ToolMobileCallExternalFunctionsRequest {
	return v.value
}

func (v *NullableToolMobileCallExternalFunctionsRequest) Set(val *ToolMobileCallExternalFunctionsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableToolMobileCallExternalFunctionsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableToolMobileCallExternalFunctionsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableToolMobileCallExternalFunctionsRequest(val *ToolMobileCallExternalFunctionsRequest) *NullableToolMobileCallExternalFunctionsRequest {
	return &NullableToolMobileCallExternalFunctionsRequest{value: val, isSet: true}
}

func (v NullableToolMobileCallExternalFunctionsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableToolMobileCallExternalFunctionsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


