/*
Moodle Webservice API

Auto-generated OpenAPI spec for Moodle's Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.

API version: 4.3.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package moodleclient

import (
	"encoding/json"
)

// checks if the CoreFilesGetFiles200ResponseParentsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CoreFilesGetFiles200ResponseParentsInner{}

// CoreFilesGetFiles200ResponseParentsInner struct for CoreFilesGetFiles200ResponseParentsInner
type CoreFilesGetFiles200ResponseParentsInner struct {
	Component *string `json:"component,omitempty"`
	Contextid *int32 `json:"contextid,omitempty"`
	Filearea *string `json:"filearea,omitempty"`
	Filename *string `json:"filename,omitempty"`
	Filepath *string `json:"filepath,omitempty"`
	Itemid *int32 `json:"itemid,omitempty"`
}

// NewCoreFilesGetFiles200ResponseParentsInner instantiates a new CoreFilesGetFiles200ResponseParentsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCoreFilesGetFiles200ResponseParentsInner() *CoreFilesGetFiles200ResponseParentsInner {
	this := CoreFilesGetFiles200ResponseParentsInner{}
	return &this
}

// NewCoreFilesGetFiles200ResponseParentsInnerWithDefaults instantiates a new CoreFilesGetFiles200ResponseParentsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCoreFilesGetFiles200ResponseParentsInnerWithDefaults() *CoreFilesGetFiles200ResponseParentsInner {
	this := CoreFilesGetFiles200ResponseParentsInner{}
	return &this
}

// GetComponent returns the Component field value if set, zero value otherwise.
func (o *CoreFilesGetFiles200ResponseParentsInner) GetComponent() string {
	if o == nil || IsNil(o.Component) {
		var ret string
		return ret
	}
	return *o.Component
}

// GetComponentOk returns a tuple with the Component field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreFilesGetFiles200ResponseParentsInner) GetComponentOk() (*string, bool) {
	if o == nil || IsNil(o.Component) {
		return nil, false
	}
	return o.Component, true
}

// HasComponent returns a boolean if a field has been set.
func (o *CoreFilesGetFiles200ResponseParentsInner) HasComponent() bool {
	if o != nil && !IsNil(o.Component) {
		return true
	}

	return false
}

// SetComponent gets a reference to the given string and assigns it to the Component field.
func (o *CoreFilesGetFiles200ResponseParentsInner) SetComponent(v string) {
	o.Component = &v
}

// GetContextid returns the Contextid field value if set, zero value otherwise.
func (o *CoreFilesGetFiles200ResponseParentsInner) GetContextid() int32 {
	if o == nil || IsNil(o.Contextid) {
		var ret int32
		return ret
	}
	return *o.Contextid
}

// GetContextidOk returns a tuple with the Contextid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreFilesGetFiles200ResponseParentsInner) GetContextidOk() (*int32, bool) {
	if o == nil || IsNil(o.Contextid) {
		return nil, false
	}
	return o.Contextid, true
}

// HasContextid returns a boolean if a field has been set.
func (o *CoreFilesGetFiles200ResponseParentsInner) HasContextid() bool {
	if o != nil && !IsNil(o.Contextid) {
		return true
	}

	return false
}

// SetContextid gets a reference to the given int32 and assigns it to the Contextid field.
func (o *CoreFilesGetFiles200ResponseParentsInner) SetContextid(v int32) {
	o.Contextid = &v
}

// GetFilearea returns the Filearea field value if set, zero value otherwise.
func (o *CoreFilesGetFiles200ResponseParentsInner) GetFilearea() string {
	if o == nil || IsNil(o.Filearea) {
		var ret string
		return ret
	}
	return *o.Filearea
}

// GetFileareaOk returns a tuple with the Filearea field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreFilesGetFiles200ResponseParentsInner) GetFileareaOk() (*string, bool) {
	if o == nil || IsNil(o.Filearea) {
		return nil, false
	}
	return o.Filearea, true
}

// HasFilearea returns a boolean if a field has been set.
func (o *CoreFilesGetFiles200ResponseParentsInner) HasFilearea() bool {
	if o != nil && !IsNil(o.Filearea) {
		return true
	}

	return false
}

// SetFilearea gets a reference to the given string and assigns it to the Filearea field.
func (o *CoreFilesGetFiles200ResponseParentsInner) SetFilearea(v string) {
	o.Filearea = &v
}

// GetFilename returns the Filename field value if set, zero value otherwise.
func (o *CoreFilesGetFiles200ResponseParentsInner) GetFilename() string {
	if o == nil || IsNil(o.Filename) {
		var ret string
		return ret
	}
	return *o.Filename
}

// GetFilenameOk returns a tuple with the Filename field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreFilesGetFiles200ResponseParentsInner) GetFilenameOk() (*string, bool) {
	if o == nil || IsNil(o.Filename) {
		return nil, false
	}
	return o.Filename, true
}

// HasFilename returns a boolean if a field has been set.
func (o *CoreFilesGetFiles200ResponseParentsInner) HasFilename() bool {
	if o != nil && !IsNil(o.Filename) {
		return true
	}

	return false
}

// SetFilename gets a reference to the given string and assigns it to the Filename field.
func (o *CoreFilesGetFiles200ResponseParentsInner) SetFilename(v string) {
	o.Filename = &v
}

// GetFilepath returns the Filepath field value if set, zero value otherwise.
func (o *CoreFilesGetFiles200ResponseParentsInner) GetFilepath() string {
	if o == nil || IsNil(o.Filepath) {
		var ret string
		return ret
	}
	return *o.Filepath
}

// GetFilepathOk returns a tuple with the Filepath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreFilesGetFiles200ResponseParentsInner) GetFilepathOk() (*string, bool) {
	if o == nil || IsNil(o.Filepath) {
		return nil, false
	}
	return o.Filepath, true
}

// HasFilepath returns a boolean if a field has been set.
func (o *CoreFilesGetFiles200ResponseParentsInner) HasFilepath() bool {
	if o != nil && !IsNil(o.Filepath) {
		return true
	}

	return false
}

// SetFilepath gets a reference to the given string and assigns it to the Filepath field.
func (o *CoreFilesGetFiles200ResponseParentsInner) SetFilepath(v string) {
	o.Filepath = &v
}

// GetItemid returns the Itemid field value if set, zero value otherwise.
func (o *CoreFilesGetFiles200ResponseParentsInner) GetItemid() int32 {
	if o == nil || IsNil(o.Itemid) {
		var ret int32
		return ret
	}
	return *o.Itemid
}

// GetItemidOk returns a tuple with the Itemid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreFilesGetFiles200ResponseParentsInner) GetItemidOk() (*int32, bool) {
	if o == nil || IsNil(o.Itemid) {
		return nil, false
	}
	return o.Itemid, true
}

// HasItemid returns a boolean if a field has been set.
func (o *CoreFilesGetFiles200ResponseParentsInner) HasItemid() bool {
	if o != nil && !IsNil(o.Itemid) {
		return true
	}

	return false
}

// SetItemid gets a reference to the given int32 and assigns it to the Itemid field.
func (o *CoreFilesGetFiles200ResponseParentsInner) SetItemid(v int32) {
	o.Itemid = &v
}

func (o CoreFilesGetFiles200ResponseParentsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CoreFilesGetFiles200ResponseParentsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Component) {
		toSerialize["component"] = o.Component
	}
	if !IsNil(o.Contextid) {
		toSerialize["contextid"] = o.Contextid
	}
	if !IsNil(o.Filearea) {
		toSerialize["filearea"] = o.Filearea
	}
	if !IsNil(o.Filename) {
		toSerialize["filename"] = o.Filename
	}
	if !IsNil(o.Filepath) {
		toSerialize["filepath"] = o.Filepath
	}
	if !IsNil(o.Itemid) {
		toSerialize["itemid"] = o.Itemid
	}
	return toSerialize, nil
}

type NullableCoreFilesGetFiles200ResponseParentsInner struct {
	value *CoreFilesGetFiles200ResponseParentsInner
	isSet bool
}

func (v NullableCoreFilesGetFiles200ResponseParentsInner) Get() *CoreFilesGetFiles200ResponseParentsInner {
	return v.value
}

func (v *NullableCoreFilesGetFiles200ResponseParentsInner) Set(val *CoreFilesGetFiles200ResponseParentsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableCoreFilesGetFiles200ResponseParentsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableCoreFilesGetFiles200ResponseParentsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCoreFilesGetFiles200ResponseParentsInner(val *CoreFilesGetFiles200ResponseParentsInner) *NullableCoreFilesGetFiles200ResponseParentsInner {
	return &NullableCoreFilesGetFiles200ResponseParentsInner{value: val, isSet: true}
}

func (v NullableCoreFilesGetFiles200ResponseParentsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCoreFilesGetFiles200ResponseParentsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


