/*
Moodle Webservice API

Auto-generated OpenAPI spec for Moodle's Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.

API version: 4.3.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package moodleclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BlockIomadCompanyAdminUpdateCoursesRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BlockIomadCompanyAdminUpdateCoursesRequest{}

// BlockIomadCompanyAdminUpdateCoursesRequest struct for BlockIomadCompanyAdminUpdateCoursesRequest
type BlockIomadCompanyAdminUpdateCoursesRequest struct {
	Courses []BlockIomadCompanyAdminUpdateCoursesRequestCoursesInner `json:"courses"`
}

type _BlockIomadCompanyAdminUpdateCoursesRequest BlockIomadCompanyAdminUpdateCoursesRequest

// NewBlockIomadCompanyAdminUpdateCoursesRequest instantiates a new BlockIomadCompanyAdminUpdateCoursesRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBlockIomadCompanyAdminUpdateCoursesRequest(courses []BlockIomadCompanyAdminUpdateCoursesRequestCoursesInner) *BlockIomadCompanyAdminUpdateCoursesRequest {
	this := BlockIomadCompanyAdminUpdateCoursesRequest{}
	this.Courses = courses
	return &this
}

// NewBlockIomadCompanyAdminUpdateCoursesRequestWithDefaults instantiates a new BlockIomadCompanyAdminUpdateCoursesRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBlockIomadCompanyAdminUpdateCoursesRequestWithDefaults() *BlockIomadCompanyAdminUpdateCoursesRequest {
	this := BlockIomadCompanyAdminUpdateCoursesRequest{}
	return &this
}

// GetCourses returns the Courses field value
func (o *BlockIomadCompanyAdminUpdateCoursesRequest) GetCourses() []BlockIomadCompanyAdminUpdateCoursesRequestCoursesInner {
	if o == nil {
		var ret []BlockIomadCompanyAdminUpdateCoursesRequestCoursesInner
		return ret
	}

	return o.Courses
}

// GetCoursesOk returns a tuple with the Courses field value
// and a boolean to check if the value has been set.
func (o *BlockIomadCompanyAdminUpdateCoursesRequest) GetCoursesOk() ([]BlockIomadCompanyAdminUpdateCoursesRequestCoursesInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Courses, true
}

// SetCourses sets field value
func (o *BlockIomadCompanyAdminUpdateCoursesRequest) SetCourses(v []BlockIomadCompanyAdminUpdateCoursesRequestCoursesInner) {
	o.Courses = v
}

func (o BlockIomadCompanyAdminUpdateCoursesRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BlockIomadCompanyAdminUpdateCoursesRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["courses"] = o.Courses
	return toSerialize, nil
}

func (o *BlockIomadCompanyAdminUpdateCoursesRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"courses",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBlockIomadCompanyAdminUpdateCoursesRequest := _BlockIomadCompanyAdminUpdateCoursesRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBlockIomadCompanyAdminUpdateCoursesRequest)

	if err != nil {
		return err
	}

	*o = BlockIomadCompanyAdminUpdateCoursesRequest(varBlockIomadCompanyAdminUpdateCoursesRequest)

	return err
}

type NullableBlockIomadCompanyAdminUpdateCoursesRequest struct {
	value *BlockIomadCompanyAdminUpdateCoursesRequest
	isSet bool
}

func (v NullableBlockIomadCompanyAdminUpdateCoursesRequest) Get() *BlockIomadCompanyAdminUpdateCoursesRequest {
	return v.value
}

func (v *NullableBlockIomadCompanyAdminUpdateCoursesRequest) Set(val *BlockIomadCompanyAdminUpdateCoursesRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBlockIomadCompanyAdminUpdateCoursesRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBlockIomadCompanyAdminUpdateCoursesRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBlockIomadCompanyAdminUpdateCoursesRequest(val *BlockIomadCompanyAdminUpdateCoursesRequest) *NullableBlockIomadCompanyAdminUpdateCoursesRequest {
	return &NullableBlockIomadCompanyAdminUpdateCoursesRequest{value: val, isSet: true}
}

func (v NullableBlockIomadCompanyAdminUpdateCoursesRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBlockIomadCompanyAdminUpdateCoursesRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


