/*
Moodle Webservice API

Auto-generated OpenAPI spec for Moodle's Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.

API version: 4.3.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package moodleclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BlockIomadCompanyAdminGetCompaniesRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BlockIomadCompanyAdminGetCompaniesRequest{}

// BlockIomadCompanyAdminGetCompaniesRequest struct for BlockIomadCompanyAdminGetCompaniesRequest
type BlockIomadCompanyAdminGetCompaniesRequest struct {
	Criteria []BlockIomadCompanyAdminGetCompaniesRequestCriteriaInner `json:"criteria"`
}

type _BlockIomadCompanyAdminGetCompaniesRequest BlockIomadCompanyAdminGetCompaniesRequest

// NewBlockIomadCompanyAdminGetCompaniesRequest instantiates a new BlockIomadCompanyAdminGetCompaniesRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBlockIomadCompanyAdminGetCompaniesRequest(criteria []BlockIomadCompanyAdminGetCompaniesRequestCriteriaInner) *BlockIomadCompanyAdminGetCompaniesRequest {
	this := BlockIomadCompanyAdminGetCompaniesRequest{}
	this.Criteria = criteria
	return &this
}

// NewBlockIomadCompanyAdminGetCompaniesRequestWithDefaults instantiates a new BlockIomadCompanyAdminGetCompaniesRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBlockIomadCompanyAdminGetCompaniesRequestWithDefaults() *BlockIomadCompanyAdminGetCompaniesRequest {
	this := BlockIomadCompanyAdminGetCompaniesRequest{}
	return &this
}

// GetCriteria returns the Criteria field value
func (o *BlockIomadCompanyAdminGetCompaniesRequest) GetCriteria() []BlockIomadCompanyAdminGetCompaniesRequestCriteriaInner {
	if o == nil {
		var ret []BlockIomadCompanyAdminGetCompaniesRequestCriteriaInner
		return ret
	}

	return o.Criteria
}

// GetCriteriaOk returns a tuple with the Criteria field value
// and a boolean to check if the value has been set.
func (o *BlockIomadCompanyAdminGetCompaniesRequest) GetCriteriaOk() ([]BlockIomadCompanyAdminGetCompaniesRequestCriteriaInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Criteria, true
}

// SetCriteria sets field value
func (o *BlockIomadCompanyAdminGetCompaniesRequest) SetCriteria(v []BlockIomadCompanyAdminGetCompaniesRequestCriteriaInner) {
	o.Criteria = v
}

func (o BlockIomadCompanyAdminGetCompaniesRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BlockIomadCompanyAdminGetCompaniesRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["criteria"] = o.Criteria
	return toSerialize, nil
}

func (o *BlockIomadCompanyAdminGetCompaniesRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"criteria",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBlockIomadCompanyAdminGetCompaniesRequest := _BlockIomadCompanyAdminGetCompaniesRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBlockIomadCompanyAdminGetCompaniesRequest)

	if err != nil {
		return err
	}

	*o = BlockIomadCompanyAdminGetCompaniesRequest(varBlockIomadCompanyAdminGetCompaniesRequest)

	return err
}

type NullableBlockIomadCompanyAdminGetCompaniesRequest struct {
	value *BlockIomadCompanyAdminGetCompaniesRequest
	isSet bool
}

func (v NullableBlockIomadCompanyAdminGetCompaniesRequest) Get() *BlockIomadCompanyAdminGetCompaniesRequest {
	return v.value
}

func (v *NullableBlockIomadCompanyAdminGetCompaniesRequest) Set(val *BlockIomadCompanyAdminGetCompaniesRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBlockIomadCompanyAdminGetCompaniesRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBlockIomadCompanyAdminGetCompaniesRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBlockIomadCompanyAdminGetCompaniesRequest(val *BlockIomadCompanyAdminGetCompaniesRequest) *NullableBlockIomadCompanyAdminGetCompaniesRequest {
	return &NullableBlockIomadCompanyAdminGetCompaniesRequest{value: val, isSet: true}
}

func (v NullableBlockIomadCompanyAdminGetCompaniesRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBlockIomadCompanyAdminGetCompaniesRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


