/*
Moodle Webservice API

Auto-generated OpenAPI spec for Moodle's Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.

API version: 4.3.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package moodleclient

import (
	"encoding/json"
)

// checks if the ModWikiGetWikisByCoursesRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModWikiGetWikisByCoursesRequest{}

// ModWikiGetWikisByCoursesRequest struct for ModWikiGetWikisByCoursesRequest
type ModWikiGetWikisByCoursesRequest struct {
	Courseids []map[string]interface{} `json:"courseids,omitempty"`
}

// NewModWikiGetWikisByCoursesRequest instantiates a new ModWikiGetWikisByCoursesRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModWikiGetWikisByCoursesRequest() *ModWikiGetWikisByCoursesRequest {
	this := ModWikiGetWikisByCoursesRequest{}
	return &this
}

// NewModWikiGetWikisByCoursesRequestWithDefaults instantiates a new ModWikiGetWikisByCoursesRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModWikiGetWikisByCoursesRequestWithDefaults() *ModWikiGetWikisByCoursesRequest {
	this := ModWikiGetWikisByCoursesRequest{}
	return &this
}

// GetCourseids returns the Courseids field value if set, zero value otherwise.
func (o *ModWikiGetWikisByCoursesRequest) GetCourseids() []map[string]interface{} {
	if o == nil || IsNil(o.Courseids) {
		var ret []map[string]interface{}
		return ret
	}
	return o.Courseids
}

// GetCourseidsOk returns a tuple with the Courseids field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModWikiGetWikisByCoursesRequest) GetCourseidsOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Courseids) {
		return nil, false
	}
	return o.Courseids, true
}

// HasCourseids returns a boolean if a field has been set.
func (o *ModWikiGetWikisByCoursesRequest) HasCourseids() bool {
	if o != nil && !IsNil(o.Courseids) {
		return true
	}

	return false
}

// SetCourseids gets a reference to the given []map[string]interface{} and assigns it to the Courseids field.
func (o *ModWikiGetWikisByCoursesRequest) SetCourseids(v []map[string]interface{}) {
	o.Courseids = v
}

func (o ModWikiGetWikisByCoursesRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModWikiGetWikisByCoursesRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Courseids) {
		toSerialize["courseids"] = o.Courseids
	}
	return toSerialize, nil
}

type NullableModWikiGetWikisByCoursesRequest struct {
	value *ModWikiGetWikisByCoursesRequest
	isSet bool
}

func (v NullableModWikiGetWikisByCoursesRequest) Get() *ModWikiGetWikisByCoursesRequest {
	return v.value
}

func (v *NullableModWikiGetWikisByCoursesRequest) Set(val *ModWikiGetWikisByCoursesRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableModWikiGetWikisByCoursesRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableModWikiGetWikisByCoursesRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModWikiGetWikisByCoursesRequest(val *ModWikiGetWikisByCoursesRequest) *NullableModWikiGetWikisByCoursesRequest {
	return &NullableModWikiGetWikisByCoursesRequest{value: val, isSet: true}
}

func (v NullableModWikiGetWikisByCoursesRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModWikiGetWikisByCoursesRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


