/*
Moodle Webservice API

Auto-generated OpenAPI spec for Moodle's Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.

API version: 4.3.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package moodleclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ToolLpDataForCompetencySummary200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ToolLpDataForCompetencySummary200Response{}

// ToolLpDataForCompetencySummary200Response struct for ToolLpDataForCompetencySummary200Response
type ToolLpDataForCompetencySummary200Response struct {
	Competency CoreCompetencyCreateCompetency200Response `json:"competency"`
	Comppath ToolLpDataForCompetencySummary200ResponseComppath `json:"comppath"`
	Framework CoreCompetencyDuplicateCompetencyFramework200Response `json:"framework"`
	// hascourses
	Hascourses bool `json:"hascourses"`
	// hasrelatedcompetencies
	Hasrelatedcompetencies bool `json:"hasrelatedcompetencies"`
	Linkedcourses []CoreCourseGetEnrolledCoursesByTimelineClassification200ResponseCoursesInner `json:"linkedcourses"`
	// pluginbaseurl
	Pluginbaseurl string `json:"pluginbaseurl"`
	Relatedcompetencies []CoreCompetencyReadUserEvidence200ResponseCompetenciesInner `json:"relatedcompetencies"`
	// scaleconfiguration
	Scaleconfiguration string `json:"scaleconfiguration"`
	// scaleid
	Scaleid int32 `json:"scaleid"`
	// taxonomyterm
	Taxonomyterm string `json:"taxonomyterm"`
}

type _ToolLpDataForCompetencySummary200Response ToolLpDataForCompetencySummary200Response

// NewToolLpDataForCompetencySummary200Response instantiates a new ToolLpDataForCompetencySummary200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewToolLpDataForCompetencySummary200Response(competency CoreCompetencyCreateCompetency200Response, comppath ToolLpDataForCompetencySummary200ResponseComppath, framework CoreCompetencyDuplicateCompetencyFramework200Response, hascourses bool, hasrelatedcompetencies bool, linkedcourses []CoreCourseGetEnrolledCoursesByTimelineClassification200ResponseCoursesInner, pluginbaseurl string, relatedcompetencies []CoreCompetencyReadUserEvidence200ResponseCompetenciesInner, scaleconfiguration string, scaleid int32, taxonomyterm string) *ToolLpDataForCompetencySummary200Response {
	this := ToolLpDataForCompetencySummary200Response{}
	this.Competency = competency
	this.Comppath = comppath
	this.Framework = framework
	this.Hascourses = hascourses
	this.Hasrelatedcompetencies = hasrelatedcompetencies
	this.Linkedcourses = linkedcourses
	this.Pluginbaseurl = pluginbaseurl
	this.Relatedcompetencies = relatedcompetencies
	this.Scaleconfiguration = scaleconfiguration
	this.Scaleid = scaleid
	this.Taxonomyterm = taxonomyterm
	return &this
}

// NewToolLpDataForCompetencySummary200ResponseWithDefaults instantiates a new ToolLpDataForCompetencySummary200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewToolLpDataForCompetencySummary200ResponseWithDefaults() *ToolLpDataForCompetencySummary200Response {
	this := ToolLpDataForCompetencySummary200Response{}
	return &this
}

// GetCompetency returns the Competency field value
func (o *ToolLpDataForCompetencySummary200Response) GetCompetency() CoreCompetencyCreateCompetency200Response {
	if o == nil {
		var ret CoreCompetencyCreateCompetency200Response
		return ret
	}

	return o.Competency
}

// GetCompetencyOk returns a tuple with the Competency field value
// and a boolean to check if the value has been set.
func (o *ToolLpDataForCompetencySummary200Response) GetCompetencyOk() (*CoreCompetencyCreateCompetency200Response, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Competency, true
}

// SetCompetency sets field value
func (o *ToolLpDataForCompetencySummary200Response) SetCompetency(v CoreCompetencyCreateCompetency200Response) {
	o.Competency = v
}

// GetComppath returns the Comppath field value
func (o *ToolLpDataForCompetencySummary200Response) GetComppath() ToolLpDataForCompetencySummary200ResponseComppath {
	if o == nil {
		var ret ToolLpDataForCompetencySummary200ResponseComppath
		return ret
	}

	return o.Comppath
}

// GetComppathOk returns a tuple with the Comppath field value
// and a boolean to check if the value has been set.
func (o *ToolLpDataForCompetencySummary200Response) GetComppathOk() (*ToolLpDataForCompetencySummary200ResponseComppath, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Comppath, true
}

// SetComppath sets field value
func (o *ToolLpDataForCompetencySummary200Response) SetComppath(v ToolLpDataForCompetencySummary200ResponseComppath) {
	o.Comppath = v
}

// GetFramework returns the Framework field value
func (o *ToolLpDataForCompetencySummary200Response) GetFramework() CoreCompetencyDuplicateCompetencyFramework200Response {
	if o == nil {
		var ret CoreCompetencyDuplicateCompetencyFramework200Response
		return ret
	}

	return o.Framework
}

// GetFrameworkOk returns a tuple with the Framework field value
// and a boolean to check if the value has been set.
func (o *ToolLpDataForCompetencySummary200Response) GetFrameworkOk() (*CoreCompetencyDuplicateCompetencyFramework200Response, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Framework, true
}

// SetFramework sets field value
func (o *ToolLpDataForCompetencySummary200Response) SetFramework(v CoreCompetencyDuplicateCompetencyFramework200Response) {
	o.Framework = v
}

// GetHascourses returns the Hascourses field value
func (o *ToolLpDataForCompetencySummary200Response) GetHascourses() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Hascourses
}

// GetHascoursesOk returns a tuple with the Hascourses field value
// and a boolean to check if the value has been set.
func (o *ToolLpDataForCompetencySummary200Response) GetHascoursesOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Hascourses, true
}

// SetHascourses sets field value
func (o *ToolLpDataForCompetencySummary200Response) SetHascourses(v bool) {
	o.Hascourses = v
}

// GetHasrelatedcompetencies returns the Hasrelatedcompetencies field value
func (o *ToolLpDataForCompetencySummary200Response) GetHasrelatedcompetencies() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Hasrelatedcompetencies
}

// GetHasrelatedcompetenciesOk returns a tuple with the Hasrelatedcompetencies field value
// and a boolean to check if the value has been set.
func (o *ToolLpDataForCompetencySummary200Response) GetHasrelatedcompetenciesOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Hasrelatedcompetencies, true
}

// SetHasrelatedcompetencies sets field value
func (o *ToolLpDataForCompetencySummary200Response) SetHasrelatedcompetencies(v bool) {
	o.Hasrelatedcompetencies = v
}

// GetLinkedcourses returns the Linkedcourses field value
func (o *ToolLpDataForCompetencySummary200Response) GetLinkedcourses() []CoreCourseGetEnrolledCoursesByTimelineClassification200ResponseCoursesInner {
	if o == nil {
		var ret []CoreCourseGetEnrolledCoursesByTimelineClassification200ResponseCoursesInner
		return ret
	}

	return o.Linkedcourses
}

// GetLinkedcoursesOk returns a tuple with the Linkedcourses field value
// and a boolean to check if the value has been set.
func (o *ToolLpDataForCompetencySummary200Response) GetLinkedcoursesOk() ([]CoreCourseGetEnrolledCoursesByTimelineClassification200ResponseCoursesInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Linkedcourses, true
}

// SetLinkedcourses sets field value
func (o *ToolLpDataForCompetencySummary200Response) SetLinkedcourses(v []CoreCourseGetEnrolledCoursesByTimelineClassification200ResponseCoursesInner) {
	o.Linkedcourses = v
}

// GetPluginbaseurl returns the Pluginbaseurl field value
func (o *ToolLpDataForCompetencySummary200Response) GetPluginbaseurl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Pluginbaseurl
}

// GetPluginbaseurlOk returns a tuple with the Pluginbaseurl field value
// and a boolean to check if the value has been set.
func (o *ToolLpDataForCompetencySummary200Response) GetPluginbaseurlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pluginbaseurl, true
}

// SetPluginbaseurl sets field value
func (o *ToolLpDataForCompetencySummary200Response) SetPluginbaseurl(v string) {
	o.Pluginbaseurl = v
}

// GetRelatedcompetencies returns the Relatedcompetencies field value
func (o *ToolLpDataForCompetencySummary200Response) GetRelatedcompetencies() []CoreCompetencyReadUserEvidence200ResponseCompetenciesInner {
	if o == nil {
		var ret []CoreCompetencyReadUserEvidence200ResponseCompetenciesInner
		return ret
	}

	return o.Relatedcompetencies
}

// GetRelatedcompetenciesOk returns a tuple with the Relatedcompetencies field value
// and a boolean to check if the value has been set.
func (o *ToolLpDataForCompetencySummary200Response) GetRelatedcompetenciesOk() ([]CoreCompetencyReadUserEvidence200ResponseCompetenciesInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Relatedcompetencies, true
}

// SetRelatedcompetencies sets field value
func (o *ToolLpDataForCompetencySummary200Response) SetRelatedcompetencies(v []CoreCompetencyReadUserEvidence200ResponseCompetenciesInner) {
	o.Relatedcompetencies = v
}

// GetScaleconfiguration returns the Scaleconfiguration field value
func (o *ToolLpDataForCompetencySummary200Response) GetScaleconfiguration() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Scaleconfiguration
}

// GetScaleconfigurationOk returns a tuple with the Scaleconfiguration field value
// and a boolean to check if the value has been set.
func (o *ToolLpDataForCompetencySummary200Response) GetScaleconfigurationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Scaleconfiguration, true
}

// SetScaleconfiguration sets field value
func (o *ToolLpDataForCompetencySummary200Response) SetScaleconfiguration(v string) {
	o.Scaleconfiguration = v
}

// GetScaleid returns the Scaleid field value
func (o *ToolLpDataForCompetencySummary200Response) GetScaleid() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Scaleid
}

// GetScaleidOk returns a tuple with the Scaleid field value
// and a boolean to check if the value has been set.
func (o *ToolLpDataForCompetencySummary200Response) GetScaleidOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Scaleid, true
}

// SetScaleid sets field value
func (o *ToolLpDataForCompetencySummary200Response) SetScaleid(v int32) {
	o.Scaleid = v
}

// GetTaxonomyterm returns the Taxonomyterm field value
func (o *ToolLpDataForCompetencySummary200Response) GetTaxonomyterm() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Taxonomyterm
}

// GetTaxonomytermOk returns a tuple with the Taxonomyterm field value
// and a boolean to check if the value has been set.
func (o *ToolLpDataForCompetencySummary200Response) GetTaxonomytermOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Taxonomyterm, true
}

// SetTaxonomyterm sets field value
func (o *ToolLpDataForCompetencySummary200Response) SetTaxonomyterm(v string) {
	o.Taxonomyterm = v
}

func (o ToolLpDataForCompetencySummary200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ToolLpDataForCompetencySummary200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["competency"] = o.Competency
	toSerialize["comppath"] = o.Comppath
	toSerialize["framework"] = o.Framework
	toSerialize["hascourses"] = o.Hascourses
	toSerialize["hasrelatedcompetencies"] = o.Hasrelatedcompetencies
	toSerialize["linkedcourses"] = o.Linkedcourses
	toSerialize["pluginbaseurl"] = o.Pluginbaseurl
	toSerialize["relatedcompetencies"] = o.Relatedcompetencies
	toSerialize["scaleconfiguration"] = o.Scaleconfiguration
	toSerialize["scaleid"] = o.Scaleid
	toSerialize["taxonomyterm"] = o.Taxonomyterm
	return toSerialize, nil
}

func (o *ToolLpDataForCompetencySummary200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"competency",
		"comppath",
		"framework",
		"hascourses",
		"hasrelatedcompetencies",
		"linkedcourses",
		"pluginbaseurl",
		"relatedcompetencies",
		"scaleconfiguration",
		"scaleid",
		"taxonomyterm",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varToolLpDataForCompetencySummary200Response := _ToolLpDataForCompetencySummary200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varToolLpDataForCompetencySummary200Response)

	if err != nil {
		return err
	}

	*o = ToolLpDataForCompetencySummary200Response(varToolLpDataForCompetencySummary200Response)

	return err
}

type NullableToolLpDataForCompetencySummary200Response struct {
	value *ToolLpDataForCompetencySummary200Response
	isSet bool
}

func (v NullableToolLpDataForCompetencySummary200Response) Get() *ToolLpDataForCompetencySummary200Response {
	return v.value
}

func (v *NullableToolLpDataForCompetencySummary200Response) Set(val *ToolLpDataForCompetencySummary200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableToolLpDataForCompetencySummary200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableToolLpDataForCompetencySummary200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableToolLpDataForCompetencySummary200Response(val *ToolLpDataForCompetencySummary200Response) *NullableToolLpDataForCompetencySummary200Response {
	return &NullableToolLpDataForCompetencySummary200Response{value: val, isSet: true}
}

func (v NullableToolLpDataForCompetencySummary200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableToolLpDataForCompetencySummary200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


