/*
Moodle Webservice API

Auto-generated OpenAPI spec for Moodle's Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.

API version: 4.3.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package moodleclient

import (
	"encoding/json"
)

// checks if the ModForumAddDiscussionRequestOptionsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModForumAddDiscussionRequestOptionsInner{}

// ModForumAddDiscussionRequestOptionsInner struct for ModForumAddDiscussionRequestOptionsInner
type ModForumAddDiscussionRequestOptionsInner struct {
	// The allowed keys (value format) are:                                         discussionsubscribe (bool); subscribe to the discussion?, default to true                                         discussionpinned    (bool); is the discussion pinned, default to false                                         inlineattachmentsid              (int); the draft file area id for inline attachments                                         attachmentsid       (int); the draft file area id for attachments                             
	Name *string `json:"name,omitempty"`
	// The value of the option,                                                             This param is validated in the external function.
	Value *string `json:"value,omitempty"`
}

// NewModForumAddDiscussionRequestOptionsInner instantiates a new ModForumAddDiscussionRequestOptionsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModForumAddDiscussionRequestOptionsInner() *ModForumAddDiscussionRequestOptionsInner {
	this := ModForumAddDiscussionRequestOptionsInner{}
	var name string = "null"
	this.Name = &name
	var value string = "null"
	this.Value = &value
	return &this
}

// NewModForumAddDiscussionRequestOptionsInnerWithDefaults instantiates a new ModForumAddDiscussionRequestOptionsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModForumAddDiscussionRequestOptionsInnerWithDefaults() *ModForumAddDiscussionRequestOptionsInner {
	this := ModForumAddDiscussionRequestOptionsInner{}
	var name string = "null"
	this.Name = &name
	var value string = "null"
	this.Value = &value
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ModForumAddDiscussionRequestOptionsInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModForumAddDiscussionRequestOptionsInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ModForumAddDiscussionRequestOptionsInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ModForumAddDiscussionRequestOptionsInner) SetName(v string) {
	o.Name = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *ModForumAddDiscussionRequestOptionsInner) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModForumAddDiscussionRequestOptionsInner) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *ModForumAddDiscussionRequestOptionsInner) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *ModForumAddDiscussionRequestOptionsInner) SetValue(v string) {
	o.Value = &v
}

func (o ModForumAddDiscussionRequestOptionsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModForumAddDiscussionRequestOptionsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	return toSerialize, nil
}

type NullableModForumAddDiscussionRequestOptionsInner struct {
	value *ModForumAddDiscussionRequestOptionsInner
	isSet bool
}

func (v NullableModForumAddDiscussionRequestOptionsInner) Get() *ModForumAddDiscussionRequestOptionsInner {
	return v.value
}

func (v *NullableModForumAddDiscussionRequestOptionsInner) Set(val *ModForumAddDiscussionRequestOptionsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableModForumAddDiscussionRequestOptionsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableModForumAddDiscussionRequestOptionsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModForumAddDiscussionRequestOptionsInner(val *ModForumAddDiscussionRequestOptionsInner) *NullableModForumAddDiscussionRequestOptionsInner {
	return &NullableModForumAddDiscussionRequestOptionsInner{value: val, isSet: true}
}

func (v NullableModForumAddDiscussionRequestOptionsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModForumAddDiscussionRequestOptionsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


