/*
Moodle Webservice API

Auto-generated OpenAPI spec for Moodle's Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.

API version: 4.3.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package moodleclient

import (
	"encoding/json"
)

// checks if the ModH5pactivityGetAttempts200ResponseUsersattemptsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModH5pactivityGetAttempts200ResponseUsersattemptsInner{}

// ModH5pactivityGetAttempts200ResponseUsersattemptsInner struct for ModH5pactivityGetAttempts200ResponseUsersattemptsInner
type ModH5pactivityGetAttempts200ResponseUsersattemptsInner struct {
	Attempts []ModH5pactivityGetAttempts200ResponseUsersattemptsInnerAttemptsInner `json:"attempts,omitempty"`
	Scored *ModH5pactivityGetAttempts200ResponseUsersattemptsInnerScored `json:"scored,omitempty"`
	// The user id
	Userid *int32 `json:"userid,omitempty"`
}

// NewModH5pactivityGetAttempts200ResponseUsersattemptsInner instantiates a new ModH5pactivityGetAttempts200ResponseUsersattemptsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModH5pactivityGetAttempts200ResponseUsersattemptsInner() *ModH5pactivityGetAttempts200ResponseUsersattemptsInner {
	this := ModH5pactivityGetAttempts200ResponseUsersattemptsInner{}
	return &this
}

// NewModH5pactivityGetAttempts200ResponseUsersattemptsInnerWithDefaults instantiates a new ModH5pactivityGetAttempts200ResponseUsersattemptsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModH5pactivityGetAttempts200ResponseUsersattemptsInnerWithDefaults() *ModH5pactivityGetAttempts200ResponseUsersattemptsInner {
	this := ModH5pactivityGetAttempts200ResponseUsersattemptsInner{}
	return &this
}

// GetAttempts returns the Attempts field value if set, zero value otherwise.
func (o *ModH5pactivityGetAttempts200ResponseUsersattemptsInner) GetAttempts() []ModH5pactivityGetAttempts200ResponseUsersattemptsInnerAttemptsInner {
	if o == nil || IsNil(o.Attempts) {
		var ret []ModH5pactivityGetAttempts200ResponseUsersattemptsInnerAttemptsInner
		return ret
	}
	return o.Attempts
}

// GetAttemptsOk returns a tuple with the Attempts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModH5pactivityGetAttempts200ResponseUsersattemptsInner) GetAttemptsOk() ([]ModH5pactivityGetAttempts200ResponseUsersattemptsInnerAttemptsInner, bool) {
	if o == nil || IsNil(o.Attempts) {
		return nil, false
	}
	return o.Attempts, true
}

// HasAttempts returns a boolean if a field has been set.
func (o *ModH5pactivityGetAttempts200ResponseUsersattemptsInner) HasAttempts() bool {
	if o != nil && !IsNil(o.Attempts) {
		return true
	}

	return false
}

// SetAttempts gets a reference to the given []ModH5pactivityGetAttempts200ResponseUsersattemptsInnerAttemptsInner and assigns it to the Attempts field.
func (o *ModH5pactivityGetAttempts200ResponseUsersattemptsInner) SetAttempts(v []ModH5pactivityGetAttempts200ResponseUsersattemptsInnerAttemptsInner) {
	o.Attempts = v
}

// GetScored returns the Scored field value if set, zero value otherwise.
func (o *ModH5pactivityGetAttempts200ResponseUsersattemptsInner) GetScored() ModH5pactivityGetAttempts200ResponseUsersattemptsInnerScored {
	if o == nil || IsNil(o.Scored) {
		var ret ModH5pactivityGetAttempts200ResponseUsersattemptsInnerScored
		return ret
	}
	return *o.Scored
}

// GetScoredOk returns a tuple with the Scored field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModH5pactivityGetAttempts200ResponseUsersattemptsInner) GetScoredOk() (*ModH5pactivityGetAttempts200ResponseUsersattemptsInnerScored, bool) {
	if o == nil || IsNil(o.Scored) {
		return nil, false
	}
	return o.Scored, true
}

// HasScored returns a boolean if a field has been set.
func (o *ModH5pactivityGetAttempts200ResponseUsersattemptsInner) HasScored() bool {
	if o != nil && !IsNil(o.Scored) {
		return true
	}

	return false
}

// SetScored gets a reference to the given ModH5pactivityGetAttempts200ResponseUsersattemptsInnerScored and assigns it to the Scored field.
func (o *ModH5pactivityGetAttempts200ResponseUsersattemptsInner) SetScored(v ModH5pactivityGetAttempts200ResponseUsersattemptsInnerScored) {
	o.Scored = &v
}

// GetUserid returns the Userid field value if set, zero value otherwise.
func (o *ModH5pactivityGetAttempts200ResponseUsersattemptsInner) GetUserid() int32 {
	if o == nil || IsNil(o.Userid) {
		var ret int32
		return ret
	}
	return *o.Userid
}

// GetUseridOk returns a tuple with the Userid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModH5pactivityGetAttempts200ResponseUsersattemptsInner) GetUseridOk() (*int32, bool) {
	if o == nil || IsNil(o.Userid) {
		return nil, false
	}
	return o.Userid, true
}

// HasUserid returns a boolean if a field has been set.
func (o *ModH5pactivityGetAttempts200ResponseUsersattemptsInner) HasUserid() bool {
	if o != nil && !IsNil(o.Userid) {
		return true
	}

	return false
}

// SetUserid gets a reference to the given int32 and assigns it to the Userid field.
func (o *ModH5pactivityGetAttempts200ResponseUsersattemptsInner) SetUserid(v int32) {
	o.Userid = &v
}

func (o ModH5pactivityGetAttempts200ResponseUsersattemptsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModH5pactivityGetAttempts200ResponseUsersattemptsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Attempts) {
		toSerialize["attempts"] = o.Attempts
	}
	if !IsNil(o.Scored) {
		toSerialize["scored"] = o.Scored
	}
	if !IsNil(o.Userid) {
		toSerialize["userid"] = o.Userid
	}
	return toSerialize, nil
}

type NullableModH5pactivityGetAttempts200ResponseUsersattemptsInner struct {
	value *ModH5pactivityGetAttempts200ResponseUsersattemptsInner
	isSet bool
}

func (v NullableModH5pactivityGetAttempts200ResponseUsersattemptsInner) Get() *ModH5pactivityGetAttempts200ResponseUsersattemptsInner {
	return v.value
}

func (v *NullableModH5pactivityGetAttempts200ResponseUsersattemptsInner) Set(val *ModH5pactivityGetAttempts200ResponseUsersattemptsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableModH5pactivityGetAttempts200ResponseUsersattemptsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableModH5pactivityGetAttempts200ResponseUsersattemptsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModH5pactivityGetAttempts200ResponseUsersattemptsInner(val *ModH5pactivityGetAttempts200ResponseUsersattemptsInner) *NullableModH5pactivityGetAttempts200ResponseUsersattemptsInner {
	return &NullableModH5pactivityGetAttempts200ResponseUsersattemptsInner{value: val, isSet: true}
}

func (v NullableModH5pactivityGetAttempts200ResponseUsersattemptsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModH5pactivityGetAttempts200ResponseUsersattemptsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


