/*
Moodle Webservice API

Auto-generated OpenAPI spec for Moodle's Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.

API version: 4.3.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package moodleclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ModBigbluebuttonbnGetBigbluebuttonbnsByCourses200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModBigbluebuttonbnGetBigbluebuttonbnsByCourses200Response{}

// ModBigbluebuttonbnGetBigbluebuttonbnsByCourses200Response struct for ModBigbluebuttonbnGetBigbluebuttonbnsByCourses200Response
type ModBigbluebuttonbnGetBigbluebuttonbnsByCourses200Response struct {
	Bigbluebuttonbns []ModBigbluebuttonbnGetBigbluebuttonbnsByCourses200ResponseBigbluebuttonbnsInner `json:"bigbluebuttonbns"`
	Warnings []AuthEmailSignupUser200ResponseWarningsInner `json:"warnings,omitempty"`
}

type _ModBigbluebuttonbnGetBigbluebuttonbnsByCourses200Response ModBigbluebuttonbnGetBigbluebuttonbnsByCourses200Response

// NewModBigbluebuttonbnGetBigbluebuttonbnsByCourses200Response instantiates a new ModBigbluebuttonbnGetBigbluebuttonbnsByCourses200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModBigbluebuttonbnGetBigbluebuttonbnsByCourses200Response(bigbluebuttonbns []ModBigbluebuttonbnGetBigbluebuttonbnsByCourses200ResponseBigbluebuttonbnsInner) *ModBigbluebuttonbnGetBigbluebuttonbnsByCourses200Response {
	this := ModBigbluebuttonbnGetBigbluebuttonbnsByCourses200Response{}
	this.Bigbluebuttonbns = bigbluebuttonbns
	return &this
}

// NewModBigbluebuttonbnGetBigbluebuttonbnsByCourses200ResponseWithDefaults instantiates a new ModBigbluebuttonbnGetBigbluebuttonbnsByCourses200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModBigbluebuttonbnGetBigbluebuttonbnsByCourses200ResponseWithDefaults() *ModBigbluebuttonbnGetBigbluebuttonbnsByCourses200Response {
	this := ModBigbluebuttonbnGetBigbluebuttonbnsByCourses200Response{}
	return &this
}

// GetBigbluebuttonbns returns the Bigbluebuttonbns field value
func (o *ModBigbluebuttonbnGetBigbluebuttonbnsByCourses200Response) GetBigbluebuttonbns() []ModBigbluebuttonbnGetBigbluebuttonbnsByCourses200ResponseBigbluebuttonbnsInner {
	if o == nil {
		var ret []ModBigbluebuttonbnGetBigbluebuttonbnsByCourses200ResponseBigbluebuttonbnsInner
		return ret
	}

	return o.Bigbluebuttonbns
}

// GetBigbluebuttonbnsOk returns a tuple with the Bigbluebuttonbns field value
// and a boolean to check if the value has been set.
func (o *ModBigbluebuttonbnGetBigbluebuttonbnsByCourses200Response) GetBigbluebuttonbnsOk() ([]ModBigbluebuttonbnGetBigbluebuttonbnsByCourses200ResponseBigbluebuttonbnsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Bigbluebuttonbns, true
}

// SetBigbluebuttonbns sets field value
func (o *ModBigbluebuttonbnGetBigbluebuttonbnsByCourses200Response) SetBigbluebuttonbns(v []ModBigbluebuttonbnGetBigbluebuttonbnsByCourses200ResponseBigbluebuttonbnsInner) {
	o.Bigbluebuttonbns = v
}

// GetWarnings returns the Warnings field value if set, zero value otherwise.
func (o *ModBigbluebuttonbnGetBigbluebuttonbnsByCourses200Response) GetWarnings() []AuthEmailSignupUser200ResponseWarningsInner {
	if o == nil || IsNil(o.Warnings) {
		var ret []AuthEmailSignupUser200ResponseWarningsInner
		return ret
	}
	return o.Warnings
}

// GetWarningsOk returns a tuple with the Warnings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModBigbluebuttonbnGetBigbluebuttonbnsByCourses200Response) GetWarningsOk() ([]AuthEmailSignupUser200ResponseWarningsInner, bool) {
	if o == nil || IsNil(o.Warnings) {
		return nil, false
	}
	return o.Warnings, true
}

// HasWarnings returns a boolean if a field has been set.
func (o *ModBigbluebuttonbnGetBigbluebuttonbnsByCourses200Response) HasWarnings() bool {
	if o != nil && !IsNil(o.Warnings) {
		return true
	}

	return false
}

// SetWarnings gets a reference to the given []AuthEmailSignupUser200ResponseWarningsInner and assigns it to the Warnings field.
func (o *ModBigbluebuttonbnGetBigbluebuttonbnsByCourses200Response) SetWarnings(v []AuthEmailSignupUser200ResponseWarningsInner) {
	o.Warnings = v
}

func (o ModBigbluebuttonbnGetBigbluebuttonbnsByCourses200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModBigbluebuttonbnGetBigbluebuttonbnsByCourses200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["bigbluebuttonbns"] = o.Bigbluebuttonbns
	if !IsNil(o.Warnings) {
		toSerialize["warnings"] = o.Warnings
	}
	return toSerialize, nil
}

func (o *ModBigbluebuttonbnGetBigbluebuttonbnsByCourses200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"bigbluebuttonbns",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varModBigbluebuttonbnGetBigbluebuttonbnsByCourses200Response := _ModBigbluebuttonbnGetBigbluebuttonbnsByCourses200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varModBigbluebuttonbnGetBigbluebuttonbnsByCourses200Response)

	if err != nil {
		return err
	}

	*o = ModBigbluebuttonbnGetBigbluebuttonbnsByCourses200Response(varModBigbluebuttonbnGetBigbluebuttonbnsByCourses200Response)

	return err
}

type NullableModBigbluebuttonbnGetBigbluebuttonbnsByCourses200Response struct {
	value *ModBigbluebuttonbnGetBigbluebuttonbnsByCourses200Response
	isSet bool
}

func (v NullableModBigbluebuttonbnGetBigbluebuttonbnsByCourses200Response) Get() *ModBigbluebuttonbnGetBigbluebuttonbnsByCourses200Response {
	return v.value
}

func (v *NullableModBigbluebuttonbnGetBigbluebuttonbnsByCourses200Response) Set(val *ModBigbluebuttonbnGetBigbluebuttonbnsByCourses200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableModBigbluebuttonbnGetBigbluebuttonbnsByCourses200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableModBigbluebuttonbnGetBigbluebuttonbnsByCourses200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModBigbluebuttonbnGetBigbluebuttonbnsByCourses200Response(val *ModBigbluebuttonbnGetBigbluebuttonbnsByCourses200Response) *NullableModBigbluebuttonbnGetBigbluebuttonbnsByCourses200Response {
	return &NullableModBigbluebuttonbnGetBigbluebuttonbnsByCourses200Response{value: val, isSet: true}
}

func (v NullableModBigbluebuttonbnGetBigbluebuttonbnsByCourses200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModBigbluebuttonbnGetBigbluebuttonbnsByCourses200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


