/*
Moodle Webservice API

Auto-generated OpenAPI spec for Moodle's Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.

API version: 4.3.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package moodleclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CoreGroupDeleteGroupMembersRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CoreGroupDeleteGroupMembersRequest{}

// CoreGroupDeleteGroupMembersRequest struct for CoreGroupDeleteGroupMembersRequest
type CoreGroupDeleteGroupMembersRequest struct {
	Members []CoreGroupDeleteGroupMembersRequestMembersInner `json:"members"`
}

type _CoreGroupDeleteGroupMembersRequest CoreGroupDeleteGroupMembersRequest

// NewCoreGroupDeleteGroupMembersRequest instantiates a new CoreGroupDeleteGroupMembersRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCoreGroupDeleteGroupMembersRequest(members []CoreGroupDeleteGroupMembersRequestMembersInner) *CoreGroupDeleteGroupMembersRequest {
	this := CoreGroupDeleteGroupMembersRequest{}
	this.Members = members
	return &this
}

// NewCoreGroupDeleteGroupMembersRequestWithDefaults instantiates a new CoreGroupDeleteGroupMembersRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCoreGroupDeleteGroupMembersRequestWithDefaults() *CoreGroupDeleteGroupMembersRequest {
	this := CoreGroupDeleteGroupMembersRequest{}
	return &this
}

// GetMembers returns the Members field value
func (o *CoreGroupDeleteGroupMembersRequest) GetMembers() []CoreGroupDeleteGroupMembersRequestMembersInner {
	if o == nil {
		var ret []CoreGroupDeleteGroupMembersRequestMembersInner
		return ret
	}

	return o.Members
}

// GetMembersOk returns a tuple with the Members field value
// and a boolean to check if the value has been set.
func (o *CoreGroupDeleteGroupMembersRequest) GetMembersOk() ([]CoreGroupDeleteGroupMembersRequestMembersInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Members, true
}

// SetMembers sets field value
func (o *CoreGroupDeleteGroupMembersRequest) SetMembers(v []CoreGroupDeleteGroupMembersRequestMembersInner) {
	o.Members = v
}

func (o CoreGroupDeleteGroupMembersRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CoreGroupDeleteGroupMembersRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["members"] = o.Members
	return toSerialize, nil
}

func (o *CoreGroupDeleteGroupMembersRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"members",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCoreGroupDeleteGroupMembersRequest := _CoreGroupDeleteGroupMembersRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCoreGroupDeleteGroupMembersRequest)

	if err != nil {
		return err
	}

	*o = CoreGroupDeleteGroupMembersRequest(varCoreGroupDeleteGroupMembersRequest)

	return err
}

type NullableCoreGroupDeleteGroupMembersRequest struct {
	value *CoreGroupDeleteGroupMembersRequest
	isSet bool
}

func (v NullableCoreGroupDeleteGroupMembersRequest) Get() *CoreGroupDeleteGroupMembersRequest {
	return v.value
}

func (v *NullableCoreGroupDeleteGroupMembersRequest) Set(val *CoreGroupDeleteGroupMembersRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCoreGroupDeleteGroupMembersRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCoreGroupDeleteGroupMembersRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCoreGroupDeleteGroupMembersRequest(val *CoreGroupDeleteGroupMembersRequest) *NullableCoreGroupDeleteGroupMembersRequest {
	return &NullableCoreGroupDeleteGroupMembersRequest{value: val, isSet: true}
}

func (v NullableCoreGroupDeleteGroupMembersRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCoreGroupDeleteGroupMembersRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


