/*
Moodle Webservice API

Auto-generated OpenAPI spec for Moodle's Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.

API version: 4.3.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package moodleclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CoreReportbuilderConditionsAdd200ResponseAvailableconditionsInnerOptiongroup type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CoreReportbuilderConditionsAdd200ResponseAvailableconditionsInnerOptiongroup{}

// CoreReportbuilderConditionsAdd200ResponseAvailableconditionsInnerOptiongroup struct for CoreReportbuilderConditionsAdd200ResponseAvailableconditionsInnerOptiongroup
type CoreReportbuilderConditionsAdd200ResponseAvailableconditionsInnerOptiongroup struct {
	// text
	Text string `json:"text"`
	Values []CoreReportbuilderConditionsAdd200ResponseAvailableconditionsInnerOptiongroupValuesInner `json:"values"`
}

type _CoreReportbuilderConditionsAdd200ResponseAvailableconditionsInnerOptiongroup CoreReportbuilderConditionsAdd200ResponseAvailableconditionsInnerOptiongroup

// NewCoreReportbuilderConditionsAdd200ResponseAvailableconditionsInnerOptiongroup instantiates a new CoreReportbuilderConditionsAdd200ResponseAvailableconditionsInnerOptiongroup object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCoreReportbuilderConditionsAdd200ResponseAvailableconditionsInnerOptiongroup(text string, values []CoreReportbuilderConditionsAdd200ResponseAvailableconditionsInnerOptiongroupValuesInner) *CoreReportbuilderConditionsAdd200ResponseAvailableconditionsInnerOptiongroup {
	this := CoreReportbuilderConditionsAdd200ResponseAvailableconditionsInnerOptiongroup{}
	this.Text = text
	this.Values = values
	return &this
}

// NewCoreReportbuilderConditionsAdd200ResponseAvailableconditionsInnerOptiongroupWithDefaults instantiates a new CoreReportbuilderConditionsAdd200ResponseAvailableconditionsInnerOptiongroup object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCoreReportbuilderConditionsAdd200ResponseAvailableconditionsInnerOptiongroupWithDefaults() *CoreReportbuilderConditionsAdd200ResponseAvailableconditionsInnerOptiongroup {
	this := CoreReportbuilderConditionsAdd200ResponseAvailableconditionsInnerOptiongroup{}
	var text string = "null"
	this.Text = text
	return &this
}

// GetText returns the Text field value
func (o *CoreReportbuilderConditionsAdd200ResponseAvailableconditionsInnerOptiongroup) GetText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Text
}

// GetTextOk returns a tuple with the Text field value
// and a boolean to check if the value has been set.
func (o *CoreReportbuilderConditionsAdd200ResponseAvailableconditionsInnerOptiongroup) GetTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Text, true
}

// SetText sets field value
func (o *CoreReportbuilderConditionsAdd200ResponseAvailableconditionsInnerOptiongroup) SetText(v string) {
	o.Text = v
}

// GetValues returns the Values field value
func (o *CoreReportbuilderConditionsAdd200ResponseAvailableconditionsInnerOptiongroup) GetValues() []CoreReportbuilderConditionsAdd200ResponseAvailableconditionsInnerOptiongroupValuesInner {
	if o == nil {
		var ret []CoreReportbuilderConditionsAdd200ResponseAvailableconditionsInnerOptiongroupValuesInner
		return ret
	}

	return o.Values
}

// GetValuesOk returns a tuple with the Values field value
// and a boolean to check if the value has been set.
func (o *CoreReportbuilderConditionsAdd200ResponseAvailableconditionsInnerOptiongroup) GetValuesOk() ([]CoreReportbuilderConditionsAdd200ResponseAvailableconditionsInnerOptiongroupValuesInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Values, true
}

// SetValues sets field value
func (o *CoreReportbuilderConditionsAdd200ResponseAvailableconditionsInnerOptiongroup) SetValues(v []CoreReportbuilderConditionsAdd200ResponseAvailableconditionsInnerOptiongroupValuesInner) {
	o.Values = v
}

func (o CoreReportbuilderConditionsAdd200ResponseAvailableconditionsInnerOptiongroup) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CoreReportbuilderConditionsAdd200ResponseAvailableconditionsInnerOptiongroup) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["text"] = o.Text
	toSerialize["values"] = o.Values
	return toSerialize, nil
}

func (o *CoreReportbuilderConditionsAdd200ResponseAvailableconditionsInnerOptiongroup) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"text",
		"values",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCoreReportbuilderConditionsAdd200ResponseAvailableconditionsInnerOptiongroup := _CoreReportbuilderConditionsAdd200ResponseAvailableconditionsInnerOptiongroup{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCoreReportbuilderConditionsAdd200ResponseAvailableconditionsInnerOptiongroup)

	if err != nil {
		return err
	}

	*o = CoreReportbuilderConditionsAdd200ResponseAvailableconditionsInnerOptiongroup(varCoreReportbuilderConditionsAdd200ResponseAvailableconditionsInnerOptiongroup)

	return err
}

type NullableCoreReportbuilderConditionsAdd200ResponseAvailableconditionsInnerOptiongroup struct {
	value *CoreReportbuilderConditionsAdd200ResponseAvailableconditionsInnerOptiongroup
	isSet bool
}

func (v NullableCoreReportbuilderConditionsAdd200ResponseAvailableconditionsInnerOptiongroup) Get() *CoreReportbuilderConditionsAdd200ResponseAvailableconditionsInnerOptiongroup {
	return v.value
}

func (v *NullableCoreReportbuilderConditionsAdd200ResponseAvailableconditionsInnerOptiongroup) Set(val *CoreReportbuilderConditionsAdd200ResponseAvailableconditionsInnerOptiongroup) {
	v.value = val
	v.isSet = true
}

func (v NullableCoreReportbuilderConditionsAdd200ResponseAvailableconditionsInnerOptiongroup) IsSet() bool {
	return v.isSet
}

func (v *NullableCoreReportbuilderConditionsAdd200ResponseAvailableconditionsInnerOptiongroup) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCoreReportbuilderConditionsAdd200ResponseAvailableconditionsInnerOptiongroup(val *CoreReportbuilderConditionsAdd200ResponseAvailableconditionsInnerOptiongroup) *NullableCoreReportbuilderConditionsAdd200ResponseAvailableconditionsInnerOptiongroup {
	return &NullableCoreReportbuilderConditionsAdd200ResponseAvailableconditionsInnerOptiongroup{value: val, isSet: true}
}

func (v NullableCoreReportbuilderConditionsAdd200ResponseAvailableconditionsInnerOptiongroup) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCoreReportbuilderConditionsAdd200ResponseAvailableconditionsInnerOptiongroup) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


