/*
Moodle Webservice API

Auto-generated OpenAPI spec for Moodle's Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.

API version: 4.3.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package moodleclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CoreFilesGetFilesRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CoreFilesGetFilesRequest{}

// CoreFilesGetFilesRequest struct for CoreFilesGetFilesRequest
type CoreFilesGetFilesRequest struct {
	// component
	Component string `json:"component"`
	// context id Set to -1 to use contextlevel and instanceid.
	Contextid int32 `json:"contextid"`
	// The context level for the file location.
	Contextlevel *string `json:"contextlevel,omitempty"`
	// file area
	Filearea string `json:"filearea"`
	// file name
	Filename string `json:"filename"`
	// file path
	Filepath string `json:"filepath"`
	// The instance id for where the file is located.
	Instanceid *int32 `json:"instanceid,omitempty"`
	// associated id
	Itemid int32 `json:"itemid"`
	// timestamp to return files changed after this time.
	Modified *int32 `json:"modified,omitempty"`
}

type _CoreFilesGetFilesRequest CoreFilesGetFilesRequest

// NewCoreFilesGetFilesRequest instantiates a new CoreFilesGetFilesRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCoreFilesGetFilesRequest(component string, contextid int32, filearea string, filename string, filepath string, itemid int32) *CoreFilesGetFilesRequest {
	this := CoreFilesGetFilesRequest{}
	this.Component = component
	this.Contextid = contextid
	var contextlevel string = "null"
	this.Contextlevel = &contextlevel
	this.Filearea = filearea
	this.Filename = filename
	this.Filepath = filepath
	var instanceid int32 = null
	this.Instanceid = &instanceid
	this.Itemid = itemid
	var modified int32 = null
	this.Modified = &modified
	return &this
}

// NewCoreFilesGetFilesRequestWithDefaults instantiates a new CoreFilesGetFilesRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCoreFilesGetFilesRequestWithDefaults() *CoreFilesGetFilesRequest {
	this := CoreFilesGetFilesRequest{}
	var contextid int32 = null
	this.Contextid = contextid
	var contextlevel string = "null"
	this.Contextlevel = &contextlevel
	var filearea string = "null"
	this.Filearea = filearea
	var filename string = "null"
	this.Filename = filename
	var filepath string = "null"
	this.Filepath = filepath
	var instanceid int32 = null
	this.Instanceid = &instanceid
	var modified int32 = null
	this.Modified = &modified
	return &this
}

// GetComponent returns the Component field value
func (o *CoreFilesGetFilesRequest) GetComponent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Component
}

// GetComponentOk returns a tuple with the Component field value
// and a boolean to check if the value has been set.
func (o *CoreFilesGetFilesRequest) GetComponentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Component, true
}

// SetComponent sets field value
func (o *CoreFilesGetFilesRequest) SetComponent(v string) {
	o.Component = v
}

// GetContextid returns the Contextid field value
func (o *CoreFilesGetFilesRequest) GetContextid() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Contextid
}

// GetContextidOk returns a tuple with the Contextid field value
// and a boolean to check if the value has been set.
func (o *CoreFilesGetFilesRequest) GetContextidOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Contextid, true
}

// SetContextid sets field value
func (o *CoreFilesGetFilesRequest) SetContextid(v int32) {
	o.Contextid = v
}

// GetContextlevel returns the Contextlevel field value if set, zero value otherwise.
func (o *CoreFilesGetFilesRequest) GetContextlevel() string {
	if o == nil || IsNil(o.Contextlevel) {
		var ret string
		return ret
	}
	return *o.Contextlevel
}

// GetContextlevelOk returns a tuple with the Contextlevel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreFilesGetFilesRequest) GetContextlevelOk() (*string, bool) {
	if o == nil || IsNil(o.Contextlevel) {
		return nil, false
	}
	return o.Contextlevel, true
}

// HasContextlevel returns a boolean if a field has been set.
func (o *CoreFilesGetFilesRequest) HasContextlevel() bool {
	if o != nil && !IsNil(o.Contextlevel) {
		return true
	}

	return false
}

// SetContextlevel gets a reference to the given string and assigns it to the Contextlevel field.
func (o *CoreFilesGetFilesRequest) SetContextlevel(v string) {
	o.Contextlevel = &v
}

// GetFilearea returns the Filearea field value
func (o *CoreFilesGetFilesRequest) GetFilearea() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Filearea
}

// GetFileareaOk returns a tuple with the Filearea field value
// and a boolean to check if the value has been set.
func (o *CoreFilesGetFilesRequest) GetFileareaOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Filearea, true
}

// SetFilearea sets field value
func (o *CoreFilesGetFilesRequest) SetFilearea(v string) {
	o.Filearea = v
}

// GetFilename returns the Filename field value
func (o *CoreFilesGetFilesRequest) GetFilename() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Filename
}

// GetFilenameOk returns a tuple with the Filename field value
// and a boolean to check if the value has been set.
func (o *CoreFilesGetFilesRequest) GetFilenameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Filename, true
}

// SetFilename sets field value
func (o *CoreFilesGetFilesRequest) SetFilename(v string) {
	o.Filename = v
}

// GetFilepath returns the Filepath field value
func (o *CoreFilesGetFilesRequest) GetFilepath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Filepath
}

// GetFilepathOk returns a tuple with the Filepath field value
// and a boolean to check if the value has been set.
func (o *CoreFilesGetFilesRequest) GetFilepathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Filepath, true
}

// SetFilepath sets field value
func (o *CoreFilesGetFilesRequest) SetFilepath(v string) {
	o.Filepath = v
}

// GetInstanceid returns the Instanceid field value if set, zero value otherwise.
func (o *CoreFilesGetFilesRequest) GetInstanceid() int32 {
	if o == nil || IsNil(o.Instanceid) {
		var ret int32
		return ret
	}
	return *o.Instanceid
}

// GetInstanceidOk returns a tuple with the Instanceid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreFilesGetFilesRequest) GetInstanceidOk() (*int32, bool) {
	if o == nil || IsNil(o.Instanceid) {
		return nil, false
	}
	return o.Instanceid, true
}

// HasInstanceid returns a boolean if a field has been set.
func (o *CoreFilesGetFilesRequest) HasInstanceid() bool {
	if o != nil && !IsNil(o.Instanceid) {
		return true
	}

	return false
}

// SetInstanceid gets a reference to the given int32 and assigns it to the Instanceid field.
func (o *CoreFilesGetFilesRequest) SetInstanceid(v int32) {
	o.Instanceid = &v
}

// GetItemid returns the Itemid field value
func (o *CoreFilesGetFilesRequest) GetItemid() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Itemid
}

// GetItemidOk returns a tuple with the Itemid field value
// and a boolean to check if the value has been set.
func (o *CoreFilesGetFilesRequest) GetItemidOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Itemid, true
}

// SetItemid sets field value
func (o *CoreFilesGetFilesRequest) SetItemid(v int32) {
	o.Itemid = v
}

// GetModified returns the Modified field value if set, zero value otherwise.
func (o *CoreFilesGetFilesRequest) GetModified() int32 {
	if o == nil || IsNil(o.Modified) {
		var ret int32
		return ret
	}
	return *o.Modified
}

// GetModifiedOk returns a tuple with the Modified field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreFilesGetFilesRequest) GetModifiedOk() (*int32, bool) {
	if o == nil || IsNil(o.Modified) {
		return nil, false
	}
	return o.Modified, true
}

// HasModified returns a boolean if a field has been set.
func (o *CoreFilesGetFilesRequest) HasModified() bool {
	if o != nil && !IsNil(o.Modified) {
		return true
	}

	return false
}

// SetModified gets a reference to the given int32 and assigns it to the Modified field.
func (o *CoreFilesGetFilesRequest) SetModified(v int32) {
	o.Modified = &v
}

func (o CoreFilesGetFilesRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CoreFilesGetFilesRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["component"] = o.Component
	toSerialize["contextid"] = o.Contextid
	if !IsNil(o.Contextlevel) {
		toSerialize["contextlevel"] = o.Contextlevel
	}
	toSerialize["filearea"] = o.Filearea
	toSerialize["filename"] = o.Filename
	toSerialize["filepath"] = o.Filepath
	if !IsNil(o.Instanceid) {
		toSerialize["instanceid"] = o.Instanceid
	}
	toSerialize["itemid"] = o.Itemid
	if !IsNil(o.Modified) {
		toSerialize["modified"] = o.Modified
	}
	return toSerialize, nil
}

func (o *CoreFilesGetFilesRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"component",
		"contextid",
		"filearea",
		"filename",
		"filepath",
		"itemid",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCoreFilesGetFilesRequest := _CoreFilesGetFilesRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCoreFilesGetFilesRequest)

	if err != nil {
		return err
	}

	*o = CoreFilesGetFilesRequest(varCoreFilesGetFilesRequest)

	return err
}

type NullableCoreFilesGetFilesRequest struct {
	value *CoreFilesGetFilesRequest
	isSet bool
}

func (v NullableCoreFilesGetFilesRequest) Get() *CoreFilesGetFilesRequest {
	return v.value
}

func (v *NullableCoreFilesGetFilesRequest) Set(val *CoreFilesGetFilesRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCoreFilesGetFilesRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCoreFilesGetFilesRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCoreFilesGetFilesRequest(val *CoreFilesGetFilesRequest) *NullableCoreFilesGetFilesRequest {
	return &NullableCoreFilesGetFilesRequest{value: val, isSet: true}
}

func (v NullableCoreFilesGetFilesRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCoreFilesGetFilesRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


